# ActiveRecord::Base.transaction do
# 	User.create!(first_name: 'Adam', last_name: 'Berman', email: 'adamberman13@gmail.com', password: 'admin1')
# 	users = []
# 	25.times do
# 		User.create!(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, password: Faker::Internet.password)
# 		users.push(User.last.id)
# 	end

# 	organizations = []
# 	25.times do
# 		Organization.create!(name: Faker::Company.name, form_date: Faker::Date.backward(10000))
# 		organizations.push(Organization.last.id)
# 	end

# 	12.times do
# 		user = User.find(users.sample)
# 		Request.create!(name: Faker::Company.bs, description: Faker::Hacker.say_something_smart, requestable: user)
# 	end

# 	13.times do
# 		organization = Organization.find(organizations.sample)
# 		Request.create!(name: Faker::Company.bs, description: Faker::Hacker.say_something_smart, requestable: organization)
# 	end

# 	Request.first.transactions.create!(respondable_id: 1, respondable_type: 'User')
# end

ActiveRecord::Base.transaction do
  Task.create!(name: "Arts, Crafts & Music")
  Task.create!(name: "Classes")
  Task.create!(name: "Crafts")
  Task.create!(name: "Entertainment")
  Task.create!(name: "Lessons")
  Task.create!(name: "Miscellaneous")
  Task.create!(name: "Photo & Video")
  Task.create!(name: "Theater")
  Task.create!(name: "Business Services")
  Task.create!(name: "Clerical")
  Task.create!(name: "Computer Support")
  Task.create!(name: "Financial")
  Task.create!(name: "Legal")
  Task.create!(name: "Marketing")
  Task.create!(name: "Miscellaneous")
  Task.create!(name: "Research")
  Task.create!(name: "Community Activities")
  Task.create!(name: "Clean-up / Recycling")
  Task.create!(name: "Community Service")
  Task.create!(name: "Free Store Volunteer")
  Task.create!(name: "Fund-raising & Grantwriting")
  Task.create!(name: "Generosity Fund Donation")
  Task.create!(name: "Group Projects")
  Task.create!(name: "Joining and Renewing Hours")
  Task.create!(name: "Miscellaneous")
  Task.create!(name: "Social Justice Projects")
  Task.create!(name: "Timebank Media Volunteering")
  Task.create!(name: "Transition & Timebank Media Projects")
  Task.create!(name: "Transition Town & Timebank Committee Work")
  Task.create!(name: "Companionship")
  Task.create!(name: "Clubs")
  Task.create!(name: "Dining Out")
  Task.create!(name: "Email / IM")
  Task.create!(name: "Home Visits")
  Task.create!(name: "Medical Errands")
  Task.create!(name: "Miscellaneous")
  Task.create!(name: "Telephone Calls")
  Task.create!(name: "Education (non-reskilling)")
  Task.create!(name: "Advocacy")
  Task.create!(name: "Classes / Workshops")
  Task.create!(name: "Computers / Technology")
  Task.create!(name: "Languages / Translation")
  Task.create!(name: "Miscellaneous")
  Task.create!(name: "Personal Finances")
  Task.create!(name: "Tutoring / Mentoring")
  Task.create!(name: "Help At Home")
  Task.create!(name: "Child Care")
  Task.create!(name: "Cooking")
  Task.create!(name: "Hair & Beauty")
  Task.create!(name: "Housekeeping / Chores")
  Task.create!(name: "Miscellaneous")
  Task.create!(name: "Pet Care")
  Task.create!(name: "Respite Care")
  Task.create!(name: "Sewing")
  Task.create!(name: "Home")
  Task.create!(name: "Car Care")
  Task.create!(name: "Carpentry / Construction")
  Task.create!(name: "Electrical")
  Task.create!(name: "Garden & Yard Work")
  Task.create!(name: "Miscellaneous")
  Task.create!(name: "Painting")
  Task.create!(name: "Plumbing")
  Task.create!(name: "Misc. (Not Above)")
  Task.create!(name: "All Other Services")
  Task.create!(name: "For Sale")
  Task.create!(name: "Free Stuff")
  Task.create!(name: "Wanted")
  Task.create!(name: "Recreation")
  Task.create!(name: "Books & Videos")
  Task.create!(name: "Dancing")
  Task.create!(name: "Events")
  Task.create!(name: "Games")
  Task.create!(name: "Miscellaneous")
  Task.create!(name: "Sports")
  Task.create!(name: "Travel")
  Task.create!(name: "Reskilling")
  Task.create!(name: "Cooking & Recipe Prep")
  Task.create!(name: "Fiber Arts")
  Task.create!(name: "Food Preservation Techniques")
  Task.create!(name: "Misc")
  Task.create!(name: "Permaculture & Gardening")
  Task.create!(name: "Soap & other cleaning supplies")
  Task.create!(name: "Tool Share")
  Task.create!(name: "Tool Share")
  Task.create!(name: "Transportation")
  Task.create!(name: "Errands / Shopping")
  Task.create!(name: "Local")
  Task.create!(name: "Long Distance")
  Task.create!(name: "Medical")
  Task.create!(name: "Miscellaneous")
  Task.create!(name: "Train / Bus / Airport")
  Task.create!(name: "Worship")
  Task.create!(name: "Wellness")
  Task.create!(name: "Complementary Therapies")
  Task.create!(name: "Counseling")
  Task.create!(name: "Diet & Nutrition")
  Task.create!(name: "Fitness & Exercise")
  Task.create!(name: "Medical Services")
  Task.create!(name: "Miscellaneous")
  Task.create!(name: "Yoga / Meditation")
end